version: '3.8'
services:
  mariadb:
    container_name: mariadb_container
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: fiveguysdb
      MARIADB_USER: fiveguys
      MARIADB_PASSWORD: fiveguys1234
      MARIADB_ROOT_PASSWORD: five1234

  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports :
      - "6379:6379"
    command:
      - redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf


  application:
    container_name: fiveguys_backend_container
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/fiveguysdb
      SPRING_DATASOURCE_USERNAME: "fiveguys"
      SPRING_DATASOURCE_PASSWORD: "fiveguys1234"
    depends_on:
      - mariadb
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
    command: ["java", "-jar", "app.jar", "--spring.config.location=file:/app/config/application.yml"]